<img src="img/Three learning problems.png"/>

# 강의

Andrew Ng - CS229 

Sung Kim - 모두를 위한 딥러닝 강좌 시즌 2

David Silver - Reinforcement Learning 

John Schulman - CS294-112 2017 Deep Reinforcement Learning

John Schulman - Deep Reinforcement Learning 

Lex Fridman - Deep Learning for Self-Driving Cars

Deep Reinforcement Learning [Pieter Abbeel](https://www.youtube.com/watch?v=ID150Tl-MMw)

A Tutorial on Reinforcement Learning by Emma Brunskill [1](https://www.youtube.com/watch?v=fIKkhoI1kF4) [2](https://www.youtube.com/watch?v=8hK0NnG_DhY)

# Book

Machine Learning, Tom Mitchell, 1997

Reinforcement Learning: An Introduction, Second edition, in progress [Richard S. Sutton and Andrew G. Barto](https://www.dropbox.com/s/b3psxv2r0ccmf80/book2015oct.pdf?dl=0) [local-slide](http://localhost:8888/notebooks/Dropbox/Paper/Reinforcement Learning - An Introduction - Second edition.pdf) [code](https://github.com/dennybritz/reinforcement-learning)

Algorithms for Reinforcement Learning [Szepesvari](https://sites.ualberta.ca/~szepesva/papers/RLAlgsInMDPs-lecture.pdf) [local-slide](http://localhost:8888/notebooks/Dropbox/Paper/Algorithms for Reinforcement Learning.pdf)

Fundamental of Reinforcement Learning 이웅원 [ebook](https://www.gitbook.com/book/dnddnjs/rl/details) [code](https://github.com/rlcode/reinforcement-learning)

Awesome Reinforcement Learning [Hyunsoo Kim, Jiwon Kim](http://aikorea.org/awesome-rl/)

dennybritz/reinforcement-learning [code](https://github.com/dennybritz/reinforcement-learning)

# Demo

[Stanford Autonomous Helicopter](http://heli.stanford.edu/) 

[Real-world demonstrations of Reinforcement Learning](http://www.dcsc.tudelft.nl/~robotics/media.html)

[Deep Q-Learning Demo - A deep Q learning demonstration using ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/rldemo.html)

[Deep Q-Learning with Tensor Flow - A deep Q learning demonstration using Google Tensorflow](https://github.com/siemanko/tensorflow-deepq)

Google DeepMind's Deep Q-Learning & Superhuman Atari Gameplays [Two Minute Papers #27](https://www.youtube.com/watch?v=Ih8EfvOzBOY) [1](https://www.youtube.com/watch?v=GACcbfUaHwc) [2](https://www.youtube.com/watch?v=tkgPvAzUbzk) [3](https://www.youtube.com/watch?v=_LEthduIbtk) [4](https://www.youtube.com/watch?v=T58HkwX-OuI) [5](https://www.youtube.com/watch?v=iqXKQf2BOSE&feature=youtu.be)

[OpenAI Gym](https://gym.openai.com/) 

# Code

[Simple Reinforcement Learning with TensorFlow](https://medium.com/emergent-future/)

[Simple reinforcement learning methods to learn CartPole](http://kvfrans.com/simple-algoritms-for-solving-cartpole/)

Deep Reinforcement Learning: Pong from Pixels [Andrej Karpathy](http://karpathy.github.io/2016/05/31/rl/)

Reinforcement-learning [rlcode](https://github.com/dennybritz/reinforcement-learning)

In [1]:
import numpy as np

np.random.permutation(10)

array([0, 3, 8, 2, 5, 7, 9, 6, 1, 4])

In [1]:
# random presenation order

import numpy as np

# size of your group
n = 25

# choose your random seed
np.random.seed(3)

# random permutation on {0,1,2,...,n}
a = np.random.permutation(n+1)
print(a)

# find where is 0
item_index = np.where(a==0)
print(item_index)

# random permutation on {1,2,...,n}
a = np.delete(a, item_index, 0)
print(a)

[18 17 12 23 15 16 13  2  1 22 14  4 21  6  7  5 20  9 11 25 19  0  8  3 24
 10]
(array([21]),)
[18 17 12 23 15 16 13  2  1 22 14  4 21  6  7  5 20  9 11 25 19  8  3 24 10]


In [2]:
# random presenation date
# 1st presenation date - Dec  1, 2017
# 2nd presenation date - Dec  8, 2017
# 3rd presenation date - Dec 15, 2017
# 4th presenation date - Dec 22, 2017

import numpy as np

# size of your group
n = 4

# choose your random seed
np.random.seed(7)

# random permutation on {0,1,2,...,n}
a = np.random.permutation(n+1)
print(a)

# find where is 0
item_index = np.where(a==0)
print(item_index)

# random permutation on {1,2,...,n}
a = np.delete(a, item_index, 0)
print(a)

group = ["A", "B", "C", "D"]
print("Dec 1, 2017: Group ", group[a[0]-1])
print("Dec 8, 2017: Group ", group[a[1]-1])
print("Dec 15, 2017: Group ", group[a[2]-1])
print("Dec 22, 2017: Group ", group[a[3]-1])

[0 3 2 1 4]
(array([0]),)
[3 2 1 4]
Dec 1, 2017: Group  C
Dec 8, 2017: Group  B
Dec 15, 2017: Group  A
Dec 22, 2017: Group  D
